use aonw_domain::TechnologyId;

// Authored recommendation priority from the reference technology catalog.
// These coordinates rank choices; clients remain free to lay out their graph.
pub(super) const fn catalog_priority(technology: TechnologyId) -> (u8, u8) {
    match technology {
        TechnologyId::Agriculture => (0, 0),
        TechnologyId::Woodworking => (1, 4),
        TechnologyId::Mining => (0, 4),
        TechnologyId::AnimalHusbandry => (1, 0),
        TechnologyId::Hunting => (0, 8),
        TechnologyId::Fishing => (1, 9),
        TechnologyId::Craftsmanship => (1, 5),
        TechnologyId::Trade => (1, 1),
        TechnologyId::Storage => (2, 0),
        TechnologyId::WaterEngineering => (2, 1),
        TechnologyId::Stoneworking => (2, 4),
        TechnologyId::MilitaryOrganization => (2, 8),
        TechnologyId::AdvancedTrade => (2, 2),
        TechnologyId::Construction => (2, 5),
        TechnologyId::Navigation => (2, 9),
        TechnologyId::Irrigation => (3, 0),
        TechnologyId::Banking => (3, 2),
        TechnologyId::Engineering => (3, 5),
        TechnologyId::Metallurgy => (3, 4),
        TechnologyId::HorsebackRiding => (3, 8),
        TechnologyId::Shipbuilding => (3, 10),
        TechnologyId::Writing => (1, 2),
        TechnologyId::Mathematics => (2, 3),
        TechnologyId::Medicine => (2, 6),
        TechnologyId::CivilService => (4, 1),
        TechnologyId::Siegecraft => (4, 10),
        TechnologyId::Cartography => (3, 11),
        TechnologyId::Guilds => (3, 6),
        TechnologyId::Law => (4, 3),
        TechnologyId::Education => (4, 0),
        TechnologyId::IronWorking => (4, 4),
        TechnologyId::CoalMining => (4, 5),
        TechnologyId::Machinery => (4, 6),
        TechnologyId::UrbanPlanning => (5, 5),
        TechnologyId::NavalDoctrine => (5, 11),
        TechnologyId::Steel => (5, 4),
        TechnologyId::Bureaucracy => (5, 1),
        TechnologyId::Nationalism => (5, 8),
        TechnologyId::Administration => (3, 1),
        TechnologyId::Logistics => (3, 9),
        TechnologyId::Tactics => (4, 9),
        TechnologyId::Economy => (4, 2),
        TechnologyId::Urbanization => (5, 0),
        TechnologyId::Fortifications => (4, 8),
        TechnologyId::Strategy => (5, 9),
        TechnologyId::Specialization => (5, 2),
        TechnologyId::ScientificMethod => (6, 0),
        TechnologyId::SteamPower => (6, 4),
        TechnologyId::Electricity => (7, 1),
        TechnologyId::Combustion => (7, 4),
        TechnologyId::Flight => (8, 2),
        TechnologyId::MassProduction => (8, 5),
        TechnologyId::Radio => (9, 2),
        TechnologyId::NuclearPhysics => (9, 0),
    }
}
